import "./globals.css";
import { Montserrat } from "next/font/google";
import Header from "@/components/header";
import clsx from "clsx";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("", montserrat.className)}>
        <Header />
        <div className="mt-24">{children}</div>
      </body>
    </html>
  );
}
